[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "./railway-start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[databases.postgresql]
version = "15"
